out_dir: results
metric_best: f1
seed: 3
num_workers: 6
wandb:
  use: True
  entity: ??
dataset:
  format: PyG-COCOSuperpixels
  name: edge_wt_region_boundary
  slic_compactness: 30
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: COCONode #+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: COCOEdge
  edge_encoder_bn: False
posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
  eval_smoothing_metrics: True
model:
  type: SSDGPSModel
  loss_fun: weighted_cross_entropy
gt:
  layer_type: CustomGatedGCN+GraphSSDLayer
  layers: 8
  n_heads: 4
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.05
  attn_dropout: 0.5
  layer_norm: True
  batch_norm: False
  use_dag_decomposition: False
  norm_position: pre
  local_norm_style: layer
  norm_style: layer
  extra_normalizer: False
  is_block_composed: True
  if_dense_bfs: False
  num_dags: 4
  d_inner: 64
  d_state: 64
  ffn_d_dinner: 128
  gnn_layernorm: False
  gnn_residual: False
  add_conv_layers: False
  conv_layers: 0
gssd:
  layer_args:
    normalize_L: False
    normalize_x: False
    broadcast_bc_in_heads: True
    norm_constraint: sum_leq
    combine_type: sum_node_edge
    use_fast_inverse: False
    graph_diameter: 200 #unused
    dt_min: 0.005
    dt_max: 0.2
    is_edge_dt: True
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_post_mp: 2
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.1
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0035
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
  batch_accumulation: 1
name_tag: FullGraph_lr0.0035_bs_32_dp0.05_seed3_dtmin5e-3_dtmax_2e-1_TM